### PR TITLE
Issue-3: Added LICENSE and shields

### LINKED ISSUE #3: Add shields to README
See https://github.com/open-horizon-services/service-homeassistant for an example of shields to add

### PR DESCRIPTION
**Pull request by joewxboy**
Signed-off-by: Joe Pearson <joewxboy@users.noreply.github.com>

Added missing Apache 2.0 license and shields.  This closes issue #3

### CODE REVIEW

**Comment by joewxboy** [comment]
@johnwalicki or @t-fine please review.

**Review by johnwalicki — APPROVED** [review]
LGTM - Thanks!

**Comment by t-fine** [comment]
@joewxboy just curious because I don't know much about the adding of these licenses; is there a reason why a service like `web-helloworld-c` has the license badge indicating `Apache-2.0` but on this service it shows up as `not specified`?

**Comment by joewxboy** [comment]
> @joewxboy just curious because I don't know much about the adding of these licenses; is there a reason why a service like `web-helloworld-c` has the license badge indicating `Apache-2.0` but on this service it shows up as `not specified`?

I suspect it's because the LICENSE wasn't there when the shields site initially checked for it.  Now that it has been added, I hope they'll resolve it overnight through some scheduled check.  Typically we'd want to add the LICENSE in a separate operation _before_ adding the license shield. :)

**Comment by t-fine** [comment]
Gotcha. I had a suspicion that might have been the case

**Pull request merged**
